---
apiVersion: v1
kind: Service
metadata:
  name: app-primeira
  namespace: app-primeira
spec:
  selector:
    app: app-primeira
  ports:
    - name: http
      port: 80
      targetPort: 5000
    - name: metrics
      port: 9999
      targetPort: 9999
