---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-primeira
  namespace: app-primeira
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: app-primeira
  endpoints:
    - port: metrics
      interval: 30s
