---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-metrics
  namespace: desafio-sre
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  namespace: monitoring
  labels:
    release: prometheus-server
spec:
  selector:
    matchLabels:
      app: flask-app
  namespaceSelector:
    matchNames:
      - desafio-sre
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
