---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: desafio-sre
data:
  # Configurações da aplicação
  REDIS_HOST: "redis-service"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
