---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: desafio-sre

resources:
  - namespace.yaml
  - app-deployment.yaml
  - app-service.yaml
  - configmap.yaml
  - ingress.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - secret.yaml
